---
- name: Setting up Python Jupyter Dev on Docker Images via SSH
  hosts: node1 # see hosts.i:w
  become: true
  become_user: root
  become_method: sudo  
  gather_facts: False # if no Python on target machine

  vars:
    - username: alpine
    - password: alpine
    - user_home_dir: "/home/{{ username }}/"
    - python36: "/usr/bin/python3.6"
    - default_jupyter: ".virtualenvs/Default3.6/bin/jupyter "  
    - default_jupyternb: "{{ default_jupyter }} notebook "  
    - default_jupyterlab: ".virtualenvs/Default3.6/bin/jupyter-lab"  
    - python_dictionary_script: "new_dict.py"
    - jupyter_ip: "0.0.0.0"
    - jupyter_port: "9999"
    - jupyter_startscript: "start_jupyter.sh"
    - jupyterlab_startscript: "start_jupyterlab.sh"
    - jupyter_notebook_dir: "{{ user_home_dir }}"
    - jupyter_params: "--ip={{ jupyter_ip }} --no-browser --NotebookApp.token={{ password }} 
                       --allow-root --notebook-dir={{ jupyter_notebook_dir }} 
                       --port={{ jupyter_port }}"
    - virtualenv_dir: "{{ user_home_dir }}/.virtualenvs"
    - req_dir: "requirements"
    - virtualenvs: 
      - {name: "Default3.6", interpreter: "{{ python36 }}", 
         rfile: "{{ req_dir }}/requirements_default36.txt"}
    - et_logo_fname: "etlogo.png"

  tasks:
  - apk:
     name: "{{ item }}"
     update_cache: yes
    with_items:
       - python3-dev
       - python3-tkinter
       - py-virtualenv
       - py3-virtualenv
       - py3-numpy
       - ca-certificates 
       - gcc 
       - vim
       - libstdc++
       - g++
       - musl-dev
       - make
       - findutils
       - tar
       - jpeg-dev 
       - zlib-dev 
       - linux-headers
       - libffi-dev 
       - openssl-dev
       - build-base 
       - libzmq 
       - zeromq-dev
       - py3-zmq
       - libxml2
       - gfortran 
       - wget 
       - libxslt-dev
       - freetype-dev 
       - libpng-dev 
       - openblas-dev
       - tk-dev
       - tcl-dev
       - git
         
  - name: Upgrade setuptools
    command: "pip3 install --upgrade pip setuptools"

  - name: Link locale.h
    file:
      src: "/usr/include/locale.h"
      dest: "/usr/include/xlocale.h"
      state: link

  - name: create the virtualenv directory
    file:
      path: "{{ virtualenv_dir }}"
      owner: "{{ username }}"
      state: directory
      mode: 0777  # "u=rw,g=wx,o=rwx"

  - name: Copy requirements to remote machine
    copy:
      src: "{{ item.rfile }}"
      dest: "{{ user_home_dir }}/requirements/"
    with_items: "{{ virtualenvs }}"
    become_user: "{{ username }}"
  
  - name: creating new virtualenv envs
    command: "virtualenv {{ virtualenv_dir}}/{{ item.name  }} -p {{item.interpreter}} creates={{ virtualenv_dir }}/{{ item.name }}"
    args:
      chdir: "{{ virtualenv_dir }}/"
    with_items: "{{ virtualenvs }}"
    become_user: "{{ username }}"
  
  # Installation of pip packages takes a long time as well 
  - name: installing pip packages
    pip: 
      requirements: "{{ user_home_dir }}/{{ item.rfile }}"
      virtualenv: "{{ virtualenv_dir }}/{{ item.name }}"
      virtualenv_python: "{{ item.interpreter }}"
    with_items: "{{ virtualenvs }}"
    become_user: "{{ username }}"

  - name: Generate Jupyter server config
    shell: "./{{ default_jupyternb }} --generate-config -y"
    become_user: "{{ username }}"

  - name: Jupyter notebook start server
    shell: "echo ./{{ default_jupyternb }} {{ jupyter_params }} > 
             {{ user_home_dir }}/{{ jupyter_startscript }}"

  - name: Jupyterlab start server
    shell: "echo ./{{ default_jupyterlab }} {{ jupyter_params }} > 
             {{ user_home_dir }}/{{ jupyterlab_startscript }}"

  - name: Change permissions of start script
    file:
      path: "{{ user_home_dir }}/{{ jupyter_startscript }}"
      owner: "{{ username }}"
      mode: "+x"

  - name: Create Jupyter custom folder
    file:
      path: "{{ user_home_dir }}/.jupyter/custom/"
      owner: "{{ username }}"
      mode: "+rw"
      state: directory
    become_user: "{{ username }}"

  - name: Create Jupyter custom.css file
    file:
      path: "{{ user_home_dir }}/.jupyter/custom/custom.css"
      owner: "{{ username }}"
      mode: "+rw"
      state: touch
    become_user: "{{ username }}"


  - name: Copy the ET logo to jupyter
    copy:
      src: "{{ et_logo_fname }}"
      dest: "{{ user_home_dir }}/.jupyter/custom/{{ et_logo_fname }}"
    become_user: "{{ username }}"

  - name: Adding custom.css for new logo in jupyter
    blockinfile:
       path: "{{ user_home_dir }}/.jupyter/custom/custom.css"
       block: |
         #ipython_notebook {
             height: 40px !important;
         }
         #ipython_notebook img{                                                                                display:block;
             background: url({{ et_logo_fname }}) no-repeat;
             background-size: contain;
             width: 233px;
             height: 33px;
             padding-left: 233px;
             -moz-box-sizing: border-box;
             box-sizing: border-box;
         }
       insertafter: EOF
  - name: Link local custom folder to root custom folder
    file:
      src: "{{ user_home_dir }}/.jupyter/custom"
      dest: "/root/.jupyter/custom"
      state: link
      force: yes

  - name: Install Jupyter notebook extensions
    shell: "./{{ default_jupyter }} contrib nbextensions install --user"
    
  - name: Install Jupyter notebook spellchecking
    shell: "./{{ default_jupyter }} nbextension enable spellchecker/main"

  - name: Copy German dictionary script 
    copy:
      src: "{{ python_dictionary_script }}"
      dest: "{{ user_home_dir }}/.jupyter/custom/{{ python_dictionary_script }}"
    register: dict_script

  - name: Run dictionary script
    shell: "{{ virtualenv_dir }}/Default3.6/bin/python3.6 {{ dict_script.dest }}"

