---
- name: Setup room for KIML course
  hosts: nodes
  become: true
  become_user: root
  become_method: su
  gather_facts: False # if no Python on target machine

  vars:
    - username: "user1"
    - user_home_dir: "/home/{{ username }}/"

  tasks:
  - user:
      name: user1
      comment: User 1
      group: sudo

  - apt:
     name: "{{ item }}"
     update_cache: yes
    with_items:
       - python3-pip
       - python3-dev
       - python3-tk
       - python3-jupyter-core
    become: true
         
  - name: Upgrade setuptools
    command: "pip3 install --upgrade pip setuptools"

  - name: installing pip packages
    pip: 
      name: "{{ item }}"
    with_items: 
      - numpy
      - scipy
      - matplotlib
      - ipython
      - scikit-learn
      - ipykernel
      - jupyter
      - jupyterlab
      - pandas
      - seaborn
      - plotly
      - bokeh
      - xlrd
      - lxml 
      - pydotplus
      - graphviz

  - name: Copy Notebooks to remote machines
    copy:
      src: "Notebooks"
      dest: "{{ user_home_dir }}/Notebooks"
  

