---
- name: Setting up ODL 2.7.2 on Docker Images via SSH
  hosts: node1 # see hosts.i:w
  become: true
  become_user: root
  become_method: sudo  
  gather_facts: False # if no Python on target machine

  vars:
    - username: alpine
    - odl_base_url: "https://nexus.opendaylight.org"
    - odl_ressource: "content/repositories/opendaylight.release/org/opendaylight/integration/karaf"
    - odl_version: "0.7.2"
    - odl_url: "{{ odl_base_url }}/{{ odl_ressource }}/{{ odl_version }}"
    - odl_tar_file: "{{ odl_url }}/karaf-{{ odl_version}}.tar.gz"
    - odl_install_dir: "/usr/local/odl"

  tasks:
  # Install openjdk8 via apk
  - apk:
     name: "{{ item }}"
     update_cache: yes
    with_items:
       - git 
       - gcc 
       - tar
       - openjdk8  # necessary for ODL
       - build-base
       - sshpass

  - name: Downloading ODL sources
    get_url:
      url: "{{ odl_tar_file }}"
      dest: "/tmp/karaf-{{ odl_version }}.tar.gz"
    register: odl_source

  - name: Ensure directory exists
    file: 
      path: "{{ odl_install_dir }}"
      state: directory
      recurse: yes
      mode: "0777"
      owner: "{{ username }}"

  - name: Unpacking ODL
    unarchive:
      remote_src: yes
      src: "{{ odl_source.dest }}"
      dest: "{{ odl_install_dir }}"
    register: odl_source_unpack 

  - name: Ensure directory exists
    file: 
      path: "{{ odl_install_dir }}"
      state: directory
      recurse: yes
      mode: "0777"
      owner: "{{ username }}"

