---
- name: Setting up ODL 2.7.2 on Docker Images via SSH
  hosts: node1 # see hosts.i:w
  become: true
  become_user: root
  become_method: sudo  

  tasks:
  - apk:
     name: "{{ item }}"
     update_cache: yes
    with_items:
       - tmux
       - mc
       - htop

